language: node_js
node_js:
  -10.16.0
cache: yarn
install:
  - yarn install
script:
  - yarn test
  - yarn  run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master